### ISSUE TITLE
reload quota periodically

### ISSUE THREAD

**Issue by goern** [thoth-station/workload-operator#19]
**Is your feature request related to a problem? Please describe.**
workload-opeator might miss some events so that it goes into a "wait for free resource forever" state. 

**Describe the solution you'd like**
Reload the resource quota information periodically, so that we can escape the deadlock. 

**Describe alternatives you've considered**
Delete the workload-operator pod, so that it is recreated and read quota on startup.

**Additional context**
n/a

**Comment by fridex** [comment]
No longer relevant. This repository will be archived as we switched to Argo workflows.
